root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main app serve"
  cmd = "templ generate && sqlc generate && go build -o ./tmp/main"
  delay = 60
  exclude_dir = ["assets", "tmp", "vendor", "data/db"]
  exclude_file = [ "go.mod", "go.sum"]
  exclude_regex = [".*_templ.go", ".*sql.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "sql"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = true
  proxy_port = 8383
  app_port = 3000
