services:
  web:
    build:
      # context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_CONN=postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-dbname}?sslmode=disable
      - LOCAL=${LOCAL}
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: ghcr.io/pgmq/pg17-pgmq:v1.5.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-dbname}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge

