@hostname=localhost:3000

GET {{hostname}}/sync/all

###
GET {{hostname}}/sync/all?lastSyncSequence=100

###

POST {{hostname}}/sync/schools
Content-Type: application/json
Accept: application/json

{
    "schools": {
        "marist": {
            "202540": 0
        }
    }
}

###

POST {{hostname}}/sync/schools
Content-Type: application/json
Accept: application/json

{
    "schools": {
        "marist": 0
    }
}

