@hostname = localhost:3000

# get all schools

GET {{hostname}}/get HTTP/1.1


### 

@school = marist

# get terms of school

GET {{hostname}}/get/{{school}}?limit=3 HTTP/1.1

###

# get terms of school

GET {{hostname}}/get/marist?limit=3&offset=3 HTTP/1.1
