@hostname = localhost:3000

GET {{hostname}}/sync/all HTTP/1.1


### 

GET {{hostname}}/sync/all?lastSyncSequence=6309&maxRecordsCount=10000 HTTP/1.1


### 

GET {{hostname}}/sync/all?lastSyncSequence=1616&maxRecordsCount=2 HTTP/1.1


### 

POST {{hostname}}/sync/schools HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "exclude": {
    "marist": {
      "202540": 12000
    }
  },
  "max_records_per_request": 10000,
  "schools": {
    "marist": {
      "202440": 0
    },
    "temple": 200
  }
}


### 

POST {{hostname}}/sync/schools HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "max_records_per_request": 10000,
  "schools": {
    "marist": {
      "202440": 0
    }
  }
}


### 

POST {{hostname}}/sync/schools HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "max_records_per_request": 10000,
  "schools": {
    "marist": 0
  }
}
