// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: manage.sql

package db

import (
	"context"
)

const getPreviousCollections = `-- name: GetPreviousCollections :exec
SELECT id, name FROM schools
`

func (q *Queries) GetPreviousCollections(ctx context.Context) error {
	_, err := q.db.Exec(ctx, getPreviousCollections)
	return err
}
